### ISSUE TITLE
Hex fields are placed outside the document

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#11]
Hex fields are placed outside the document:

![outsidedoc](https://user-images.githubusercontent.com/406414/34663202-f1637ffc-f455-11e7-8164-cf376408ad65.png)

(created with the changes in #9)

**Comment by lifelike** [comment]
Was not an issue as long as grid was only 1px wide. :) Will have to include the width in calculations from now on then.

**Comment by lifelike** [comment]
Should be fixed now. Workaround is not very pretty, but it looks like everything is where it should be.
