### ISSUE TITLE
Error: Preview with "optional" Parameter

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#13]
Settings: Default
Action: Click on Preview
![hexpreview](https://user-images.githubusercontent.com/406414/46036752-9f37d100-c106-11e8-96c3-24efdd811934.png)

**Comment by lifelike** [comment]
Oops. Should not happen. Currently rewriting that code anyway to use it also for stroke-width, so will consider this to make sure it is fixed in the next commit.
