### ISSUE TITLE
Feature Request: Make all „Hex ....“ layers as sublayers of „Hexmap“

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#22]
Right now the extension creates independent layers at the top of the layer hierachy. For me it would be usefull to get **one layer** in the top hierachy with sublayers for the used options.

**Comment by lifelike** [comment]
This could be an option, but I would not want it (and not have it as a default) since I tend to mix the hex layers with other layers, not treat them as a combined thing.

**Comment by lifelike** [comment]
Now there is an option in the Layers tab to group all layers in a Hex Map group layer.
