### ISSUE TITLE
Remove/Raise maximum number of rows and columns

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#23]
For my project I need more than 1000 rows/columns, so it's a little problem that the maximal value is hardcoded:

https://github.com/lifelike/hexmapextension/blob/c14764eeac6efc11aa79e6b118b0e57ad9ec2f73/hexmap.inx#L12

If the value of 1000 is chosen freely and there have to be a fix value, I suggest to raise it.

**Comment by lifelike** [comment]
Max and min are mandatory, but I increased the max values to 1000000. Hope that is enough.
Much lower values than that would kill my computer, and I never saw a game with anywhere close to 1000 rows or columns, so I thought that was overkill already. :)
