### ISSUE TITLE
What is size of "brick" based on hex size

### ISSUE THREAD

**Issue by jrvjrv** [lifelike/hexmapextension#26]
The hex size determines the point-to-point size of the hexes (based on experiments I have performed). (this also seems to be true when the hexes are rotated: https://github.com/lifelike/hexmapextension/issues/1). How is the hex size value is related to brick size when style is set to brick?

**Comment by jrvjrv** [comment]
I experimented and determined that the bricks are drawn with their centers in the same place as the hex centers would be for hexagons. That means that the width of a brick is 3/4 of the hex size value and the height of the brick is √3/2 (square root of 3 over two, 0.866) times the hex size value (this is also the height of the hexagon).

In this picture I have drawn hexagons and bricks (in green) both with hex size one centimeter. The distance from point to point on the hexagons is one centimeter, the distance from side to side of the bricks is 0.75 centimeter, and the height of both the bricks and the hexagons is 0.866 centimeter.

![hexmap_extension_trim](https://user-images.githubusercontent.com/7386638/59616938-67891300-90f3-11e9-85f3-1b5e3ab65eab.png)

If you choose "force square" bricks (not shown in picture), the squares are one centimeter by one centimeter. The bricks do not line up with the sides of the page (unlike the hexagons). I have not determined how the value of the margin is calculated.

**Comment by lifelike** [comment]
Thanks for reporting this and taking the time to solve it. :) That would be great to add to the documentation, like maybe the wiki here on github, in case someone else is curious? Indeed the bricks are created by just deforming the hexagons, keeping the centers where they were.
