### ISSUE TITLE
Hex Map featured in my new book

### ISSUE THREAD

**Issue by WSzP** [lifelike/hexmapextension#3]
Hi Pelle,
Just wanted to thank you for the great Hexmap extension. Did you know that Hexmap is featured in my new book, User Experience Mapping. To be precise in chapter 10 (page 297) with a screenshot and instructions. I introduce this as a better way to create hexagon maps with Inkscape. Hexagon maps are needed for ecosystem maps. Obviously I gave credit to you as creator of the tool, mentioning your name and the github url to Hex Map Extension.

The book is available on Amazon, just search "User Experience Mapping - Peter W. Szabo" (published by Packt Publishing).

Have a great day and thanks for the extension.
Peter
(@wszp on Twitter)

**Comment by lifelike** [comment]
Happy it could be of use and in a context I was not expecting. Thanks for mentioning it!

I subscribe to Safari Books Online and just read the chapter there, so I guess I can close this issue now.  :)
