### ISSUE TITLE
"No module named lxml" but I have it installed

### ISSUE THREAD

**Issue by dosaki** [lifelike/hexmapextension#31]
When trying to create a hex-grid (using the default values), I get the error below:

> The fantastic lxml wrapper for libxml2 is required by inkex.py and therefore this extension.Please download and install the latest version from http://cheeseshop.python.org/pypi/lxml/, or install it through your package manager by a command like: sudo apt-get install python-lxml
> 
> Technical details:
> No module named lxml

But I have `lxml` installed:
```bash
$ sudo pip install lxml
Requirement already satisfied: lxml in /usr/lib/python3.7/site-packages (4.4.0)
```

And I can use it:
![image](https://user-images.githubusercontent.com/1957450/62403911-784cf580-b588-11e9-8e5a-7e17e260a55d.png)

I'm using Anarchy Linux and these are the versions I'm using:
```bash
$ inkscape --version && python --version && uname -a
Inkscape 0.92.4 5da689c313, 2019-01-14
Python 3.7.4
Linux metztli 5.2.5-arch1-1-ARCH #1 SMP PREEMPT Wed Jul 31 08:30:34 UTC 2019 x86_64 GNU/Linux
```

**Comment by lifelike** [comment]
I suspect that you need to install lxml for python 2 as well? As far as I know Inkscape python extensions are still executed with python 2.

Do any other inkscape extensions run for you that require lxml (probably most of them do)?

**Comment by dosaki** [comment]
That was it. Thanks!

Had to install `python2-pip` and then run
```bash
sudo pip2 install lxml
```

Had no idea inkscape still used python 2.7!
