### ISSUE TITLE
QQ regarding Square Grid options

### ISSUE THREAD

**Issue by rjbprime** [lifelike/hexmapextension#35]
I have a question, that may be an enhancement or not, or may be addressed elsewhere. Is there a way, with this extension or something similar, to create non-offset square grids, such as those used mainly in Dungeons & Dragons / Pathfinder type battle maps?

As I would like to automate creating a grid with co-ordinates, which your extension does for the hex and offset grid, but have no coding ability with python.

Is this something that could be added, or is this not a part of the intended design?

**Comment by lifelike** [comment]
I have considered it, mostly to re-use the code for coordinate numberings, but almost everything else would be a complete rewrite as there are so many assumptions about things being 6-sided. It is not just a matter of removing the offsets, unfortunately.

**Comment by rjbprime** [comment]
That fair enough. I did manage to work out a way of doing what I wanted, using a combination of Excel, Notepad++, and PS.

Basically, in Excel, created the initial co-ords, dragged them to the amount needed, then saved the file as a tab separated txt file. Then, in Notepad++, formatted how I wanted with search and replacement. Then, in PS, created a text box on my map I was using, and sized it accordingly.

If it's not going to be a part of the code, then I'll close this issue.
