### ISSUE TITLE
Column Alpha Coordinates broken for Python 3

### ISSUE THREAD

**Issue by paulmelis** [lifelike/hexmapextension#39]
The line `/usr/bin/env python` in `hexmap.py` might resolve to Python 3.x for some users (including me). The division for `d` in 

https://github.com/lifelike/hexmapextension/blob/11401e23889318bdefb72df6980393050299d8cc/hexmap.py#L36-L39

then no longer returns an integer with Python 3, but a float value (as `/` is changed in Py 3). Which causes an issue for the return value. Replacing `d = c / 26` with `d = c // 26` fixes it and also works in Python 2.

**Comment by lifelike** [comment]
This was fixed by commit 58e9830cf9f5841a112743b9f05b4bf1a0b60a6f by Mario Voigt as part of updating this extension to work with Inkscape 1.0.
