### ISSUE TITLE
Border size option

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#4]
An option to define the border size would be nice.

**Comment by lifelike** [comment]
I have thought of adding an option to use the bounding box of the current selection. I think that would be a good way to precisely add borders as well.

**Comment by pmjdebruijn** [comment]
This might be addressed by #9

**Comment by lifelike** [comment]
I read this issue as being about the border around the entire grid (more like print margins around the edges of the page)?

**Comment by sennewood** [comment]
I meant the thickness of the lines of the hexagons.

**Comment by lifelike** [comment]
Oh.  Then #9 pr should do the trick. :)

**Comment by sennewood** [comment]
I tried #9 and experienced that a value <1 pt is impossible. Maybe pt isn't the best unit for the work with vectors.

**Comment by pmjdebruijn** [comment]
1 pt is just an arbitrary minimum set in the .inx file, you can probably change that to 0.1

**Comment by lifelike** [comment]
I plan to change it to a text input instead anyway so that any unit can be used. Still has to be some kind of error-checking to avoid crazy/negative values, but less than 1 should be ok.

**Comment by lifelike** [comment]
Accepted the pr, then reduced the minimum to 0.1 pt. Should definitely change that (as well as the hex size entry) to be a string value that can include any unit.
