### ISSUE TITLE
Kudos and a blog post

### ISSUE THREAD

**Issue by gizmomathboy** [lifelike/hexmapextension#40]
I just want to say that I find your extension useful and welcome.

I mention it in a blog post:

https://opensourcegamer.com/blog/blog/2020/09/21/i-need-a-hex-map/

So, keep up the good work.

I certainly appreciate it.

gizmo

**Comment by lifelike** [comment]
Great to hear and nice to see you got the different size hexes to line up that well. I never tried that trick. (Also, hexcrawling is something I would like to try sometime, as a GM or player.)
