### ISSUE TITLE
filling a Pages

### ISSUE THREAD

**Issue by ashnansen** [lifelike/hexmapextension#42]
It woud be nice if I was able to fill a standart A4 or A1 pages and with a margan on 20 mm for holes. 
The scalling of Top - Botom is not working, but the Left - Right is.

**Comment by lifelike** [comment]
See the user guide. The algorithm for filling the page is not extremely clever or always the best possible.

If you want to make room for the holes I recommend setting the Document Properties size of the page to be small enough to fit the area you actually want to print on. It can always be reset to the full size of the paper after generating the grid.
