### ISSUE TITLE
Documentation: Inkscape Flatpak installation location

### ISSUE THREAD

**Issue by FilBot3** [lifelike/hexmapextension#43]
This isn't really an issue, but more of a documentation note for those using Inkscape in a Flatpak. You'll want to drop these files into the:

```
${HOME}/.var/app/org.inkscape.Inkscape/config/inkscape/extensions/
```

Then restart Inkscape.

**Comment by lifelike** [comment]
I do not think it is feasible to cover all possible installation directories, but I guess Flatpak may be popular enough to be worth mentioning. Want to add it to the wiki? I am not sure how it works, but I think it is editable not only to me?

**Comment by lifelike** [comment]
Never mind it is in the README. I was confused. Will add that.
