### ISSUE TITLE
More hex size units or more digits

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#7]
I want fields with a size of 5mm, but I cant enter the correct value because only 3 digits after the comma are allowed and 5mm = 0.1968504in. To get a value with 3 digits after the comma, I have to raise the number to 50000mm (1968.504in), but then the extension set the value back to 10.000.

**Comment by lifelike** [comment]
I was a bit lazy. Should definitely accept numbers with units so you can input 5 mm.

**Comment by sennewood** [comment]
How is it going? :)

**Comment by lifelike** [comment]
Going slow! Thanks for reminding me.

**Comment by lifelike** [comment]
Now?

**Comment by sennewood** [comment]
Pretty good, thank you :)

**Comment by sennewood** [comment]
It would be nice to set the stroke size also in mm (now in pt).

**Comment by lifelike** [comment]
I thought of adding that as well, but was not sure if anyone would want it. But you are right it can be a bit confusing to set the size in pt if the hex width is in some other unit.
